RU = {'api_id_input': 'Введите api_id с раздела API сайта https://my.telegram.org/ [→] ',
      'api_hash_input': 'Введите api_hash с раздела API сайта https://my.telegram.org/ [→] ',
      'success_api': 'api_id и api_hash валидны, продолжаем настройку',
      'error_api': 'api_id или api_hash не подходят, попробуйте заново',
      'phone_input': 'Введите номер телефона для подключения вашего аккаунта [→] ',
      'phone_error': 'Номер телефона не существует, попробуйте снова',
      'code_input': 'Введите код подтверждения отправленный вам в телеграм [→] ',
      'code_success': 'Вход подтверждён, аккаунт подключён',
      'code_error': 'Ошибка входа, попробуйте снова',
      'choose': 'Выберите действие:\n\t1 - Сменить язык\n\t2 - Запустить LambdaStealer\n[→] ',
      'lang_success': 'Язык был успешно сменён',
      'starting': 'Запуск LambdaStealer, подождите пожалуйста\n\tЧтобы остановить бота нажмите Ctrl+C или удалите сессию\n\n'}

ENG = {'api_id_input': 'Enter the api_id from the API section of the site https://my.telegram.org/ [→] ',
      'api_hash_input': 'Enter the api_hash from the API section of the site https://my.telegram.org/ [→] ',
      'success_api': 'api_id and api_hash are valid, we continue to configure',
      'error_api': 'api_id or api_hash are invalid, try again',
      'phone_input': 'Enter the phone number to connect your account [→] ',
      'phone_error': 'Phone number is invalid, try again',
      'code_input': 'Enter the confirmation code sent to you in telegram [→] ',
      'code_success': 'Login is confirmed, account connected',
      'code_error': 'Login error, try again',
      'choose': 'Select an action:\n\t1 - Change language\n\t2 - Start LambdaStealler\n[→] ',
      'lang_success': 'Language was successfully changed',
      'starting': 'starting LambdaStealer, wait please\n\tTo stop the bot press Ctrl+C or delete session\n\n'}
      